---
certificate_authority_name: WolkCA

kubernetes_version: "v1.18.6"
kubernetes_etcd_version: v3.4.10

kubernetes_public_port: 6443
kubernetes_local_port: "{{ kubernetes_public_port }}"
kubernetes_etcd_peer_port: 2380
kubernetes_etcd_client_port: 2379
kubernetes_service_node_port_range: 30000-32767
kubernetes_etcd_initial_token: kubdoc
